/**
 * Copyright (c) 2022 PROPHESSOR
 * 
 * This software is released under the MIT License.
 * https://opensource.org/licenses/MIT
 */

import { CompletionItemKind } from "vscode";
import { explodeString, ICompletionTree } from "../utils";

const type = CompletionItemKind;

export default [
  ...explodeString(type.Function, "ForceField|Teleport_EndGameActivatorTID|CancelFade|ClearInventory|ClearLineSpecial|GameSkill|GameType|GetLineRowOffset|GetScreenHeight|GetScreenWidth|GetSigilPieces|GetWeapon|LineSide"),

  { name: "ACS_Execute", description: "int script|[int mapnum]|[int s_arg1]|[int s_arg2]|[int s_arg3]", docs: "Executes the specified script. Only one copy of the script can be running at a time when started using this function.", type: type.Function },
  { name: "ACS_ExecuteAlways", description: "int script|[int mapnum]|[int arg1]|[int arg2]|[int arg3]", docs: "Executes the specified script. Multiple copies of the script can be running at the same time when started using this function|however they can not be suspended or terminated.", type: type.Function },
  { name: "ACS_ExecuteWithResult", description: "int script|[int s_arg1]|[int s_arg2]|[int s_arg3]|[int s_arg4]", docs: "Executes the specified script and returns the value set in the script by SetResultValue", type: type.Function },
  { name: "ACS_LockedExecute", description: "int script|[int mapnum]|[int arg1]|[int arg2]|[int lock]", docs: "Executes the specified script if the player has the right key. Displays the 'remote' locked message.", type: type.Function },
  { name: "ACS_LockedExecuteDoor", description: "int script|[int mapnum]|[int arg1]|[int arg2]|[int lock]", docs: "Executes the specified script if the player has the right key. Displays the 'door' locked message.", type: type.Function },
  { name: "ACS_Suspend", description: "int script|[int mapnum]", docs: "Suspends execution of the specified script. Use ACS_Execute or ACS_LockedExecute to resume the script.", type: type.Function },
  { name: "ACS_Terminate", description: "int script|[int mapnum]", docs: "Terminates execution of the specified script.", type: type.Function },
  { name: "Autosave", docs: "Automatically saves the game to an autosave slot.", type: type.Function },

  { name: "Ceiling_CrushAndRaise", description: "int tag|int speed|int damage|[int crushmode]", type: type.Function },
  { name: "Ceiling_CrushAndRaiseA", description: "int tag|int downspeed|int upspeed|int damage|[int crushmode]", type: type.Function },
  { name: "Ceiling_CrushAndRaiseDist", description: "int tag|int dist|int speed|int damage|[int crushmode]", type: type.Function },
  { name: "Ceiling_CrushAndRaiseSilentA", description: "int tag|int downspeed|int upspeed|int damage|[int crushmode]", type: type.Function },
  { name: "Ceiling_CrushAndRaiseSilentDist", description: "int tag|int dist|int speed|int damage|[int crushmode]", type: type.Function },
  { name: "Ceiling_CrushRaiseAndStay", description: "int tag|int speed|int damage|[int crushmode]", type: type.Function },
  { name: "Ceiling_CrushRaiseAndStayA", description: "int tag|int downspeed|int upspeed|int damage|[int crushmode]", type: type.Function },
  { name: "Ceiling_CrushRaiseAndStaySilA", description: "int tag|int downspeed|int upspeed|int damage|[int crushmode]", type: type.Function },
  { name: "Ceiling_CrushStop", description: "int tag", type: type.Function },
  { name: "Ceiling_LowerAndCrush", description: "int tag|int speed|int damage|[int crushmode]", type: type.Function },
  { name: "Ceiling_LowerAndCrushDist", description: "int tag|int speed|int damage|int dist|[int crushmode]", type: type.Function },
  { name: "Ceiling_LowerByTexture", description: "int tag|int speed|[int change]|[int damage]", type: type.Function },
  { name: "Ceiling_LowerByValue", description: "int tag|int speed|int value", type: type.Function },
  { name: "Ceiling_LowerByValueTimes8", description: "int tag|int speed|int value", type: type.Function },
  { name: "Ceiling_LowerInstant", description: "int tag|int unused|int value", type: type.Function },
  { name: "Ceiling_LowerToFloor", description: "int tag|int speed", type: type.Function },
  { name: "Ceiling_LowerToHighestFloor", description: "int tag|int speed", type: type.Function },
  { name: "Ceiling_LowerToLowest", description: "int tag|int speed", type: type.Function },
  { name: "Ceiling_LowerToNearest", description: "int tag|int speed|[int change]|[int damage]", type: type.Function },
  { name: "Ceiling_MoveToValue", description: "int tag|int speed|int value|int negative", type: type.Function },
  { name: "Ceiling_MoveToValueAndCrush", description: "int tag|int speed|int value|int damage|[int crushmode]", type: type.Function },
  { name: "Ceiling_MoveToValueTimes8", description: "int tag|int speed|int value|int negative", type: type.Function },
  { name: "Ceiling_RaiseByTexture", description: "int tag|int speed|[int change]", type: type.Function },
  { name: "Ceiling_RaiseByValue", description: "int tag|int speed|int value", type: type.Function },
  { name: "Ceiling_RaiseByValueTimes8", description: "int tag|int speed|int value", type: type.Function },
  { name: "Ceiling_RaiseInstant", description: "int tag|int unused|int value", type: type.Function },
  { name: "Ceiling_RaiseToHighest", description: "int tag|int speed|[int change]", type: type.Function },
  { name: "Ceiling_RaiseToHighestFloor", description: "int tag|int speed|[int change]", type: type.Function },
  { name: "Ceiling_RaiseToLowest", description: "int tag|int speed|[int change]", type: type.Function },
  { name: "Ceiling_RaiseToNearest", description: "int tag|int speed", type: type.Function },
  { name: "Ceiling_Stop", description: "int tag", type: type.Function },
  { name: "Ceiling_ToFloorInstant", description: "int tag|[int change]|[int damage]|[int gap]", type: type.Function },
  { name: "Ceiling_ToHighestInstant", description: "int tag|[int change]|[int damage]", type: type.Function },
  { name: "Ceiling_Waggle", description: "int tag|int amplitude|int frequency|int delay|int time", type: type.Function },
  { name: "ChangeCamera", description: "int tid|int who|int revert", type: type.Function },
  { name: "ChangeSkill", description: "int level", type: type.Function },
  { name: "ClearForceField", description: "int tag", type: type.Function },
  { name: "DamageThing", description: "int damage|[int mod]", type: type.Function },
  { name: "Door_Animated", description: "int tag|int speed|int delay|int lock", type: type.Function },
  { name: "Door_AnimatedClose", description: "int tag|int speed", type: type.Function },
  { name: "Door_Close", description: "int tag|int speed|[int lighttag]", type: type.Function },
  { name: "Door_CloseWaitOpen", description: "int tag|int speed|int delay|[int lighttag]", type: type.Function },
  { name: "Door_LockedRaise", description: "int tag|int speed|int delay|int lock|[int lighttag]", type: type.Function },
  { name: "Door_Open", description: "int tag|int speed|[int lighttag]", type: type.Function },
  { name: "Door_Raise", description: "int tag|int speed|int delay|[int lighttag]", type: type.Function },
  { name: "Door_WaitClose", description: "int tag|int speed|int wait|[int lighttag]", type: type.Function },
  { name: "Door_WaitRaise", description: "int tag|int speed|int delay|int wait|[int lighttag]", type: type.Function },
  { name: "Elevator_LowerToNearest", description: "int tag|int speed", type: type.Function },
  { name: "Elevator_MoveToFloor", description: "int tag|int speed", type: type.Function },
  { name: "Elevator_RaiseToNearest", description: "int tag|int speed", type: type.Function },
  { name: "Exit_Normal", description: "int position", type: type.Function },
  { name: "Exit_Secret", description: "int position", type: type.Function },
  { name: "Floor_CrushStop", description: "int tag", type: type.Function },
  { name: "Floor_Donut", description: "int pillartag|int pillarspeed|int moatspeed", type: type.Function },
  { name: "Floor_LowerByTexture", description: "int tag|int speed|[int change]", type: type.Function },
  { name: "Floor_LowerByValue", description: "int tag|int speed|int value", type: type.Function },
  { name: "Floor_LowerByValueTimes8", description: "int tag|int speed|int value", type: type.Function },
  { name: "Floor_LowerInstant", description: "int tag|int unused|int value", type: type.Function },
  { name: "Floor_LowerToHighest", description: "int tag|int speed|int adjust|[int always]", type: type.Function },
  { name: "Floor_LowerToHighestEE", description: "int tag|int speed|[int change]", type: type.Function },
  { name: "Floor_LowerToLowest", description: "int tag|int speed", type: type.Function },
  { name: "Floor_LowerToLowestCeiling", description: "int tag|int speed|[int change]", type: type.Function },
  { name: "Floor_LowerToLowestTxTy", description: "int tag|int speed", type: type.Function },
  { name: "Floor_LowerToNearest", description: "int tag|int speed", type: type.Function },
  { name: "Floor_MoveToValue", description: "int tag|int speed|int value|int negative", type: type.Function },
  { name: "Floor_MoveToValueAndCrush", description: "int tag|int speed|int value|int damage|[int crushmode]", type: type.Function },
  { name: "Floor_MoveToValueTimes8", description: "int tag|int speed|int value|int negative", type: type.Function },
  { name: "Floor_RaiseAndCrush", description: "int tag|int speed|int damage|[int crushmode]", type: type.Function },
  { name: "Floor_RaiseAndCrushDoom", description: "int tag|int speed|int damage|[int crushmode]", type: type.Function },
  { name: "Floor_RaiseByTexture", description: "int tag|int speed", type: type.Function },
  { name: "Floor_RaiseByValue", description: "int tag|int speed|int value", type: type.Function },
  { name: "Floor_RaiseByValueTimes8", description: "int tag|int speed|int value", type: type.Function },
  { name: "Floor_RaiseByValueTxTy", description: "int tag|int speed|int value", type: type.Function },
  { name: "Floor_RaiseInstant", description: "int tag|int unused|int value", type: type.Function },
  { name: "Floor_RaiseToCeiling", description: "int tag|int speed|[int change]|[int damage]|[int gap]", type: type.Function },
  { name: "Floor_RaiseToHighest", description: "int tag|int speed", type: type.Function },
  { name: "Floor_RaiseToLowest", description: "int tag|int change|[int damage]", type: type.Function },
  { name: "Floor_RaiseToLowestCeiling", description: "int tag|int speed", type: type.Function },
  { name: "Floor_RaiseToNearest", description: "int tag|int speed", type: type.Function },
  { name: "Floor_Stop", description: "int tag", type: type.Function },
  { name: "Floor_ToCeilingInstant", description: "int tag|[int change]|[int damage]|[int gap]", type: type.Function },
  { name: "Floor_TransferNumeric", description: "int tag", type: type.Function },
  { name: "Floor_TransferTrigger", description: "int tag", type: type.Function },
  { name: "Floor_Waggle", description: "int tag|int amp|int freq|int offset|int time", type: type.Function },
  { name: "FloorAndCeiling_LowerByValue", description: "int tag|int speed|int value", type: type.Function },
  { name: "FloorAndCeiling_LowerRaise", description: "int tag|int floor_speed|int ceiling_speed|[int boom1998]", type: type.Function },
  { name: "FloorAndCeiling_RaiseByValue", description: "int tag|int speed|int value", type: type.Function },

  { name: "FS_Execute", description: "int script|[int frontonly]|[int lock]|[int lockedmessage]", type: type.Function },
  { name: "Generic_Ceiling", description: "int tag|int speed|int height|int target|int flags", type: type.Function },
  { name: "Generic_Crusher", description: "int tag|int downspeed|int upspeed|int silent|int damage", type: type.Function },
  { name: "Generic_Crusher2", description: "int tag|int downspeed|int upspeed|int silent|int damage", type: type.Function },
  { name: "Generic_Door", description: "int tag|int speed|int kind|int delay|int lock", type: type.Function },
  { name: "Generic_Floor", description: "int tag|int speed|int height|int target|int flags", type: type.Function },
  { name: "Generic_Lift", description: "int tag|int speed|int delay|int target|int height", type: type.Function },
  { name: "Generic_Stairs", description: "int tag|int speed|int step|int flags|int reset", type: type.Function },
  { name: "GlassBreak", description: "[int nojunk]", type: type.Function },
  { name: "HealThing", description: "amount|[int max]", type: type.Function },
  { name: "Light_ChangeToValue", description: "int tag|int value", type: type.Function },
  { name: "Light_Fade", description: "int tag|int value|int tics", type: type.Function },
  { name: "Light_Flicker", description: "int tag|int upper|int lower", type: type.Function },
  { name: "Light_ForceLightning", description: "int mode", type: type.Function },
  { name: "Light_Glow", description: "int tag|int upper|int lower|int tics", type: type.Function },
  { name: "Light_LowerByValue", description: "int tag|int value", type: type.Function },
  { name: "Light_MaxNeighbor", description: "int tag", type: type.Function },
  { name: "Light_MinNeighbor", description: "int tag", type: type.Function },
  { name: "Light_RaiseByValue", description: "int tag|int value", type: type.Function },
  { name: "Light_Stop", description: "int tag", type: type.Function },
  { name: "Light_Strobe", description: "int tag|int upper|int lower|int u-tics|int l-tics", type: type.Function },
  { name: "Light_StrobeDoom", description: "int tag|int u-tics|int l-tics", type: type.Function },
  { name: "Line_AlignCeiling", description: "int lineid|int side", type: type.Function },
  { name: "Line_AlignFloor", description: "int lineid|int side", type: type.Function },
  { name: "Line_SetAutomapFlags", description: "int lineid|int setflags|int clearflags", type: type.Function },
  { name: "Line_SetAutomapStyle", description: "int lineid|int style", type: type.Function },
  { name: "Line_SetBlocking", description: "int lineid|int setflags|int clearflags", type: type.Function },
  { name: "Line_SetHealth", description: "int lineid|int health", type: type.Function },
  { name: "Line_SetPortalTarget", description: "int sourceline|int targetline", type: type.Function },
  { name: "Line_SetTextureOffset", description: "int id|int x|int y|int side|int flags", type: type.Function },
  { name: "Line_SetTextureScale", description: "int id|int x|int y|int side|int flags", type: type.Function },
  { name: "NoiseAlert", description: "int target_tid|int emitter_tid", type: type.Function },
  { name: "Pillar_Build", description: "int tag|int speed|int value", type: type.Function },
  { name: "Pillar_BuildAndCrush", description: "int tag|int speed|int value|int damage|int crushmode", type: type.Function },
  { name: "Pillar_Open", description: "int tag|int speed|int floor|int ceiling", type: type.Function },
  { name: "Plat_DownByValue", description: "int tag|int speed|int delay|int value", type: type.Function },
  { name: "Plat_DownWaitUpStay", description: "int tag|int speed|int delay", type: type.Function },
  { name: "Plat_DownWaitUpStayLip", description: "int tag|int speed|int delay|int lip|int sound", type: type.Function },
  { name: "Plat_PerpetualRaise", description: "int tag|int speed|int delay", type: type.Function },
  { name: "Plat_PerpetualRaiseLip", description: "int tag|int speed|int delay|int lip", type: type.Function },
  { name: "Plat_RaiseAndStayTx0", description: "int tag|int speed|[int lockout]", type: type.Function },
  { name: "Plat_Stop", description: "int tag", type: type.Function },
  { name: "Plat_ToggleCeiling", description: "int tag", type: type.Function },
  { name: "Plat_UpByValue", description: "int tag|int speed|int delay|int value", type: type.Function },
  { name: "Plat_UpByValueStayTx", description: "int tag|int speed|int value", type: type.Function },
  { name: "Plat_UpNearestWaitDownStay", description: "int tag|int speed|int delay", type: type.Function },
  { name: "Plat_UpWaitDownStay", description: "int tag|int speed|int delay", type: type.Function },
  { name: "Polyobj_DoorSlide", description: "int po|int speed|int angle|int dist|int delay", type: type.Function },
  { name: "Polyobj_DoorSwing", description: "int po|int speed|int angle|int delay", type: type.Function },
  { name: "Polyobj_Move", description: "int po|int speed|int angle|int dist", type: type.Function },
  { name: "Polyobj_MoveTimes8", description: "int po|int speed|int angle|int dist", type: type.Function },
  { name: "Polyobj_MoveTo", description: "int po|int speed|int x|int y", type: type.Function },
  { name: "Polyobj_MoveToSpot", description: "int po|int speed|int tid", type: type.Function },
  { name: "Polyobj_OR_Move", description: "int po|int speed|int angle|int distance", type: type.Function },
  { name: "Polyobj_OR_MoveTimes8", description: "int po|int speed|int angle|int distance", type: type.Function },
  { name: "Polyobj_OR_MoveTo", description: "int po|int speed|int x|int y", type: type.Function },
  { name: "Polyobj_OR_MoveToSpot", description: "int po|int speed|int tid", type: type.Function },
  { name: "Polyobj_OR_RotateLeft", description: "int po|int speed|int angle", type: type.Function },
  { name: "Polyobj_OR_RotateRight", description: "int po|int speed|int angle", type: type.Function },
  { name: "Polyobj_RotateLeft", description: "int po|int speed|int angle", type: type.Function },
  { name: "Polyobj_RotateRight", description: "int po|int speed|int angle", type: type.Function },
  { name: "Polyobj_Stop", description: "int po", type: type.Function },
  { name: "Polyobj_StopSound", description: "int po", type: type.Function },
  { name: "Radius_Quake", description: "int intensity|int duration|int damrad|int tremrad|int tid", type: type.Function },
  { name: "Scroll_Ceiling", description: "int tag|int x-move|int y-move|int unused", type: type.Function },
  { name: "Scroll_Floor", description: "int tag|int x-move|int y-move|int mode", type: type.Function },
  { name: "Scroll_Texture_Both", description: "int lineid|int left|int right|int up|int down", type: type.Function },
  { name: "Scroll_Wall", description: "int lineid|int x|int y|int side|int flags", type: type.Function },
  { name: "Sector_ChangeFlags", description: "int tag|int set|int clear", type: type.Function },
  { name: "Sector_ChangeSound", description: "int tag|int newsequence", type: type.Function },
  { name: "Sector_SetCeilingGlow", description: "int tag|int height|int red|int green|int blue", type: type.Function },
  { name: "Sector_SetCeilingPanning", description: "int tag|int x-int|int x-frac|int y-int|int y-frac", type: type.Function },
  { name: "Sector_SetCeilingScale", description: "int tag|int x-int|int x-frac|int y-int|int y-frac", type: type.Function },
  { name: "Sector_SetCeilingScale2", description: "int tag|int x-factor|int y-factor", type: type.Function },
  { name: "Sector_SetColor", description: "int tag|int r|int g|int b|int desaturate", type: type.Function },
  { name: "Sector_SetCurrent", description: "int tag|int amount|int angle|int useline", type: type.Function },
  { name: "Sector_SetDamage", description: "int tag|int amount|int mod|int interval|int leaky", type: type.Function },
  { name: "Sector_SetFade", description: "int tag|int r|int g|int b", type: type.Function },
  { name: "Sector_SetFloorGlow", description: "int tag|int height|int red|int green|int blue", type: type.Function },
  { name: "Sector_SetFloorPanning", description: "int tag|int x-int|int x-frac|int y-int|int y-frac", type: type.Function },
  { name: "Sector_SetFloorScale", description: "int tag|int x-int|int x-frac|int y-int|int y-frac", type: type.Function },
  { name: "Sector_SetFloorScale2", description: "int tag|int x-factor|int y-factor", type: type.Function },
  { name: "Sector_SetFriction", description: "int tag|int amount", type: type.Function },
  { name: "Sector_SetGravity", description: "int tag|int intpart|int fracpart", type: type.Function },
  { name: "Sector_SetHealth", description: "int tag|int part|int health", type: type.Function },
  { name: "Sector_SetLink", description: "int controltag|int linktag|int floor/ceiling|int movetype", type: type.Function },
  { name: "Sector_SetPlaneReflection", description: "int tag|int floor|int ceiling", type: type.Function },
  { name: "Sector_SetRotation", description: "int tag|int floor-angle|int ceiling-angle", type: type.Function },
  { name: "Sector_SetTranslucent", description: "int tag|int plane|int amount|int type", type: type.Function },
  { name: "Sector_SetWind", description: "int tag|int amount|int angle|int useline", type: type.Function },
  { name: "SendToCommunicator", description: "int voc_num|int front-only|int identify|int nolog", type: type.Function },
  { name: "SetGlobalFogParameter", description: "int type|int value", type: type.Function },
  { name: "SetPlayerProperty", description: "int allplayers|int value|int which", type: type.Function },
  { name: "Stairs_BuildDown", description: "int tag|int speed|int height|int delay|int reset", type: type.Function },
  { name: "Stairs_BuildDownDoom", description: "int tag|int speed|int height|int delay|int reset", type: type.Function },
  { name: "Stairs_BuildDownDoomSync", description: "int tag|int speed|int height|int reset", type: type.Function },
  { name: "Stairs_BuildDownSync", description: "int tag|int speed|int height|int reset", type: type.Function },
  { name: "Stairs_BuildUp", description: "int tag|int speed|int height|int delay|int reset", type: type.Function },
  { name: "Stairs_BuildUpDoom", description: "int tag|int speed|int height|int delay|int reset", type: type.Function },
  { name: "Stairs_BuildUpDoomCrush", description: "int tag|int speed|int height|int delay|int reset", type: type.Function },
  { name: "Stairs_BuildUpDoomSync", description: "int tag|int speed|int height|int reset", type: type.Function },
  { name: "Stairs_BuildUpSync", description: "int tag|int speed|int height|int reset", type: type.Function },
  { name: "StartConversation", description: "int tid|[int facetalker]", type: type.Function },
  { name: "Teleport", description: "int tid|int tag|int nosourcefog", type: type.Function },
  { name: "Teleport_Line", description: "int thisid|int destid|[int reversed]", type: type.Function },
  { name: "Teleport_NewMap", description: "int map|int pos|[int keepangle]", type: type.Function },
  { name: "Teleport_NoFog", description: "int tid|[int useang]|[int sectortag]|[int keepheight]", type: type.Function },
  { name: "Teleport_NoStop", description: "int tid|int sectortag|[int nosourcefog]", type: type.Function },
  { name: "Teleport_ZombieChanger", description: "int tid|int sectortag", type: type.Function },
  { name: "TeleportGroup", description: "int group_tid|int source_tid|int dest_tid|int move_source|int use_fog", type: type.Function },
  { name: "TeleportInSector", description: "int tag|int source_tid|int dest_tid|int use_fog|[int group_tid]", type: type.Function },
  { name: "TeleportOther", description: "int other_tid|int dest_tid|[int fog]", type: type.Function },
  { name: "Thing_Activate", description: "int tid", type: type.Function },
  { name: "Thing_ChangeTID", description: "int oldtid|int newtid", type: type.Function },
  { name: "Thing_Damage", description: "int tid|int amount|int mod", type: type.Function },
  { name: "Thing_Deactivate", description: "int tid", type: type.Function },
  { name: "Thing_Destroy", description: "int tid|[int extreme]|[int sector_tag]", type: type.Function },
  { name: "Thing_Hate", description: "int hater|int hatee|[int flags]", type: type.Function },
  { name: "Thing_Move", description: "int tid|int mapspot|[int nofog]", type: type.Function },
  { name: "Thing_Projectile", description: "int tid|int type|int angle|int speed|int vspeed", type: type.Function },
  { name: "Thing_ProjectileAimed", description: "int tid|int type|int speed|int target|[int newtid]", type: type.Function },
  { name: "Thing_ProjectileGravity", description: "int tid|int type|int angle|int speed|int vspeed", type: type.Function },
  { name: "Thing_ProjectileIntercept", description: "int tid|int type|int speed|int target|int newtid", type: type.Function },
  { name: "Thing_Raise", description: "int tid", type: type.Function },
  { name: "Thing_Remove", description: "int tid", type: type.Function },
  { name: "Thing_SetConversation", description: "int tid|conv_id", type: type.Function },
  { name: "Thing_SetGoal", description: "int tid|int goal|int delay|[int chasegoal]", type: type.Function },
  { name: "Thing_SetSpecial", description: "int tid|int special|int arg1|int arg2|int arg3", type: type.Function },
  { name: "Thing_SetTranslation", description: "int tid|int translation_num", type: type.Function },
  { name: "Thing_Spawn", description: "int tid|int type|int angle|[int newtid]", type: type.Function },
  { name: "Thing_SpawnFacing", description: "int tid|int type|[int nofog]|[int newtid]", type: type.Function },
  { name: "Thing_SpawnNoFog", description: "int tid|int type|int angle|[int newtid]", type: type.Function },
  { name: "Thing_Stop", description: "int tid", type: type.Function },
  { name: "ThrustThing", description: "int angle|int force|[int limit]|[int tid]", type: type.Function },
  { name: "ThrustThingZ", description: "int tid|int zthrust|int dir|int set", type: type.Function },
  { name: "TranslucentLine", description: "int id|int amount|int transtype", type: type.Function },
  { name: "UsePuzzleItem", description: "int item|int script", type: type.Function },

  { name: "ACS_ExecuteWait", description: "int script|int unused|int arg1|int arg2|int arg3", type: type.Function },
  { name: "ACS_NamedExecute", description: "str script|[int mapnum]|[int s_arg1]|[int s_arg2]|[int s_arg3]", type: type.Function },
  { name: "ACS_NamedExecuteAlways", description: "str script|[int mapnum]|[int arg1]|[int arg2]|[int arg3]", type: type.Function },
  { name: "ACS_NamedExecuteWait", description: "str script|int unused|int arg1|int arg2|int arg3", type: type.Function },
  { name: "ACS_NamedExecuteWithResult", description: "str script|[int s_arg1]|[int s_arg2]|[int s_arg3]|[int s_arg4]", type: type.Function },
  { name: "ACS_NamedLockedExecute", description: "str script|[int mapnum]|[int arg1]|[int arg2]|[int lock]", type: type.Function },
  { name: "ACS_NamedLockedExecuteDoor", description: "str script|[int mapnum]|[int arg1]|[int arg2]|[int lock]", type: type.Function },
  { name: "ACS_NamedSuspend", description: "str script|[int mapnum]", type: type.Function },
  { name: "ACS_NamedTerminate", description: "str script|[int mapnum]", type: type.Function },
  { name: "ActivatorSound", description: "str sound|int volume", type: type.Function },

  { name: "AmbientSound", description: "str sound|int volume", type: type.Function },

  { name: "CanRaiseActor", description: "int tid", type: type.Function },
  { name: "Ceil", description: "fixed value", type: type.Function },
  { name: "ChangeActorAngle", description: "int tid|fixed angle|[bool interpolate]", type: type.Function },
  { name: "ChangeActorPitch", description: "int tid|fixed pitch|[bool interpolate]", type: type.Function },
  { name: "ChangeActorRoll", description: "int tid|fixed angle|[bool interpolate]", type: type.Function },
  { name: "ChangeCeiling", description: "int tag|str flatname", type: type.Function },
  { name: "ChangeFloor", description: "int tag|str flatname", type: type.Function },
  { name: "ChangeLevel", description: "str mapname|int position|int flags,[ int skill]", type: type.Function },
  { name: "ChangeSky", description: "str sky1|str sky2", type: type.Function },
  { name: "CheckActorCeilingTexture", description: "int tid|str texture", type: type.Function },
  { name: "CheckActorClass", description: "int tid|str class", type: type.Function },
  { name: "CheckActorFloorTexture", description: "int tid|str texture", type: type.Function },
  { name: "CheckActorInventory", description: "int tid|str inventory_item", type: type.Function },
  { name: "CheckActorProperty", description: 'int tid|int property|int value" | "int tid|int property|float value" | "int tid|int property|str value', type: type.Function },
  { name: "CheckActorState", description: "int tid|str statename|[bool exact]", type: type.Function },
  { name: "CheckClass", description: "str classname", type: type.Function },
  { name: "CheckFlag", description: "int tid|str flag", type: type.Function },
  { name: "CheckFont", description: "str fontname", type: type.Function },
  { name: "CheckInventory", description: "str inventory_item", type: type.Function },
  { name: "CheckPlayerCamera", description: "int player", type: type.Function },
  { name: "CheckProximity", description: "int tid|str classname|fixed distance|[int count]|[int flags]|[int pointer]", type: type.Function },
  { name: "CheckSight", description: "int source|int dest|[int flags]", type: type.Function },
  { name: "CheckWeapon", description: "str weapon", type: type.Function },
  { name: "ClassifyActor", description: "int tid", type: type.Function },
  { name: "ClearActorInventory", description: "int tid", type: type.Function },

  { name: "Cos", description: "int angle", type: type.Function },
  { name: "CreateTranslation", description: 'int transnumber|a:b=c:d|..." | "int transnumber|a:b=[red1,green1,blue1]:[red2,green2,blue2]|...', type: type.Function },
  { name: "DamageActor", description: "int target_tid|int target_pointer|int inflictor_tid|int inflictor_pointer|int amount|str damagetype", type: type.Function },
  { name: "Delay", description: "int tics", type: type.Function },
  { name: "DropInventory", description: "int tid|str item", type: type.Function },
  { name: "DropItem", description: "int tid|str item|[int dropamount]|[int chance]", type: type.Function },
  { name: "FadeRange", description: "int red1|int green1|int blue1|fixed amount1|int red2|int green2|int blue2|fixed amount2|fixed seconds", type: type.Function },
  { name: "FadeTo", description: "int red|int green|int blue|fixed amount|fixed seconds", type: type.Function },
  { name: "FixedDiv", description: "fixed a|fixed b", type: type.Function },
  { name: "FixedMul", description: "fixed a|fixed b", type: type.Function },
  { name: "FixedSqrt", description: "fixed number", type: type.Function },
  { name: "Floor", description: "fixed value", type: type.Function },

  { name: "GetActorAngle", description: "int tid", type: type.Function },
  { name: "GetActorCeilingZ", description: "int tid", type: type.Function },
  { name: "GetActorClass", description: "int tid", type: type.Function },
  { name: "GetActorFloorTerrain", description: "int tid", type: type.Function },
  { name: "GetActorFloorTexture", description: "int tid", type: type.Function },
  { name: "GetActorFloorZ", description: "int tid", type: type.Function },
  { name: "GetActorLightLevel", description: "int tid", type: type.Function },
  { name: "GetActorPitch", description: "int tid", type: type.Function },
  { name: "GetActorPowerupTics", description: "int tid|str powerup", type: type.Function },
  { name: "GetActorProperty", description: "int tid|int property", type: type.Function },
  { name: "GetActorRoll", description: "int tid", type: type.Function },
  { name: "GetActorVelX", description: "int tid", type: type.Function },
  { name: "GetActorVelY", description: "int tid", type: type.Function },
  { name: "GetActorVelZ", description: "int tid", type: type.Function },
  { name: "GetActorViewHeight", description: "int tid", type: type.Function },
  { name: "GetActorX", description: "int tid", type: type.Function },
  { name: "GetActorY", description: "int tid", type: type.Function },
  { name: "GetActorZ", description: "int tid", type: type.Function },
  { name: "GetAirSupply", description: "int playernum", type: type.Function },
  { name: "GetAmmoCapacity", description: "str classname", type: type.Function },
  { name: "GetArmorInfo", description: "int infotype", type: type.Function },
  { name: "GetArmorType", description: "string armortype|int playernum", type: type.Function },
  { name: "GetChar", description: "str string|int index", type: type.Function },
  { name: "GetCVar", description: "str cvar", type: type.Function },
  { name: "GetCVarString", description: "str cvarname", type: type.Function },
  { name: "GetLevelInfo", description: "int levelinfo", type: type.Function },
  { name: "GetLineActivation", description: "int lineid", type: type.Function },
  { name: "GetLineHealth", description: "int lineid", type: type.Function },

  { name: "GetLineUDMFFixed", description: "int lineid|str key", type: type.Function },
  { name: "GetLineUDMFInt", description: "int lineid|str key", type: type.Function },
  { name: "GetLineX", description: "unknown parameter list", type: type.Function },
  { name: "GetLineY", description: "unknown parameter list", type: type.Function },
  { name: "GetMaxInventory", description: "int tid|str inventory", type: type.Function },
  { name: "GetPlayerInfo", description: "int playernumber|int playerinfo", type: type.Function },
  { name: "GetPlayerInput", description: "int player|int input", type: type.Function },
  { name: "GetPolyobjX", description: "int polynum", type: type.Function },
  { name: "GetPolyobjY", description: "int polynum", type: type.Function },

  { name: "GetSectorCeilingZ", description: "int tag|int x|int y", type: type.Function },
  { name: "GetSectorFloorZ", description: "int tag|int x|int y", type: type.Function },
  { name: "GetSectorHealth", description: "int tag|int part", type: type.Function },
  { name: "GetSectorLightLevel", description: "int tag", type: type.Function },
  { name: "GetSectorUDMFFixed", description: "int tag|string key", type: type.Function },
  { name: "GetSectorUDMFInt", description: "int tag|string key", type: type.Function },
  { name: "GetSideUDMFFixed", description: "int lineid|bool back|string key", type: type.Function },
  { name: "GetSideUDMFInt", description: "int lineid|bool back|string key", type: type.Function },

  { name: "GetThingUDMFFixed", description: "int tid|string key", type: type.Function },
  { name: "GetThingUDMFInt", description: "int tid|string key", type: type.Function },
  { name: "GetUserArray", description: "int tid|str name|int pos", type: type.Function },
  { name: "GetUserCVar", description: "int playernum|str cvarname", type: type.Function },
  { name: "GetUserCVarString", description: "int playernum|str cvarname", type: type.Function },
  { name: "GetUserVariable", description: "int tid|str name", type: type.Function },

  { name: "GiveActorInventory", description: "int tid|str inventory_item|int amount", type: type.Function },
  { name: "GiveInventory", description: "str inventory_item|int amount", type: type.Function },
  { name: "HudMessage", description: 'text; int type|int id|int color|fixed x|fixed y|fixed holdTime|alpha" | "text; HUDMSG_FADEOUT|int id|int color|fixed x|fixed y|fixed holdTime|fixed fadetime|alpha" | "text; HUDMSG_TYPEON|int id|int color|fixed x|fixed y|fixed holdTime|fixed typetime|fixed fadetime|alpha" | "text; HUDMSG_FADEINOUT|int id|int color|fixed x|fixed y|fixed holdTime|fixed inTime|fixed outTime|alpha', type: type.Function },
  { name: "HudMessageBold", description: 'text; int type|int id|int color|fixed x|fixed y|fixed holdTime|alpha" | "text; HUDMSG_FADEOUT|int id|int color|fixed x|fixed y|fixed holdTime|fixed fadetime|alpha" | "text; HUDMSG_TYPEON|int id|int color|fixed x|fixed y|fixed holdTime|fixed typetime|fixed fadetime|alpha" | "text; HUDMSG_FADEINOUT|int id|int color|fixed x|fixed y|fixed holdTime|fixed inTime|fixed outTime|alpha', type: type.Function },
  { name: "IsPointerEqual", description: "int ptr_select1|int ptr_select2|[int tid1]|[int tid2]", type: type.Function },
  { name: "IsTIDUsed", description: "int tid", type: type.Function },

  { name: "LineAttack", description: "int tid|fixed angle|fixed pitch|int damage|[str pufftype]|[str damagetype]|[fixed range]|[int flags]|[int pufftid]", type: type.Function },
  { name: "LocalAmbientSound", description: "str sound|int volume", type: type.Function },
  { name: "LocalSetMusic", description: "str song|[int order]", type: type.Function },
  { name: "Log", description: "type:expression", type: type.Function },
  { name: "MorphActor", description: "int tid|[str playerclass]|[str monsterclass]|[int duration]|[int style]|[str morphflash]|[str unmorphflash]", type: type.Function },
  { name: "NamedScriptWait", description: "str script", type: type.Function },
  { name: "PickActor", description: "int source_tid|fixed angle|fixed pitch|fixed distance|int new_tid|[int actor_mask]|[int wall_mask]|[int flags]", type: type.Function },
  { name: "PlayActorSound", description: "int tid|int sound|[int channel]|[fixed volume]|[bool looping]|[fixed attenuation]", type: type.Function },
  { name: "PlayerClass", description: "int playernumber", type: type.Function },

  { name: "PlayerCount", type: type.Function },
  { name: "PlayerFrags", type: type.Function },
  { name: "PlayerInGame", description: "int playernumber", type: type.Function },
  { name: "PlayerIsBot", description: "int playernumber", type: type.Function },
  { name: "PlayerNumber", type: type.Function },
  { name: "PlayMovie", description: "str moviename - but this function does not work anyway", type: type.Function },
  { name: "PlaySound", description: "int tid|str sound|[int channel]|[fixed volume]|[bool looping]|[fixed attenuation]|[bool local]", type: type.Function },
  { name: "PolyWait", description: "int polynum", type: type.Function },
  { name: "Print", description: "type:expression", type: type.Function },
  { name: "PrintBold", description: "type:expression", type: type.Function },
  { name: "QuakeEx", description: "int tid|int intensityX|int intensityY|int intensityZ|int duration|int damrad|int tremrad|sound sfx|[int flags]|[fixed mulWaveX]|[fixed mulWaveY]|[fixed mulWaveZ]|[int falloff]|[int highpoint]|[fixed rollIntensity]|[fixed rollWave]", type: type.Function },
  { name: "Radius_Quake2", description: "int tid|int intensity|int duration|int damrad|int tremrad|str sound", type: type.Function },
  { name: "Random", description: "int min|int max", type: type.Function },
  { name: "ReplaceTextures", description: "str oldtexturename|str newtexturename|[int flags]", type: type.Function },
  { name: "Round", description: "fixed value", type: type.Function },
  { name: "ScriptCall", description: "str classname|str funcname|args", type: type.Function },
  { name: "ScriptWait", description: "int script", type: type.Function },
  { name: "SectorDamage", description: "int tag|int amount|str type|str protection_item|int flags", type: type.Function },
  { name: "SectorSound", description: "str sound|int volume", type: type.Function },
  { name: "SetActivator", description: "int tid|[int pointer_selector]", type: type.Function },
  { name: "SetActivatorToTarget", description: "int tid", type: type.Function },
  { name: "SetActorAngle", description: "int tid|fixed angle", type: type.Function },
  { name: "SetActorFlag", description: "int tid|str flagname|bool set", type: type.Function },
  { name: "SetActorPitch", description: "int tid|fixed pitch", type: type.Function },
  { name: "SetActorPosition", description: "int tid|fixed x|fixed y|fixed z|bool fog", type: type.Function },
  { name: "SetActorProperty", description: 'int tid|int property|int value" | "int tid|int property|float value" | "int tid|int property|str value', type: type.Function },
  { name: "SetActorRoll", description: "int tid|fixed angle", type: type.Function },
  { name: "SetActorState", description: "int tid|str statename|[bool exact]", type: type.Function },
  { name: "SetActorTeleFog", description: "int tid|str sourcefog|str destfog", type: type.Function },
  { name: "SetActorVelocity", description: "int tid|fixed velx|fixed vely|fixed velz|bool add|bool setbob", type: type.Function },
  { name: "SetAirControl", description: "int amount", type: type.Function },
  { name: "SetAirSupply", description: "int playernum|int tics", type: type.Function },
  { name: "SetAmmoCapacity", description: "str typename|int maxamount", type: type.Function },
  { name: "SetCameraToTexture", description: "int cameratid|str texturename|int fov", type: type.Function },
  { name: "SetCeilingTrigger", description: "int tag|int height|int special|[int arg1]|[int arg2]|[int arg3]|[int arg4]|[int arg5]", type: type.Function },
  { name: "SetCVar", description: 'str cvarname|int newvalue" | "str cvarname|fixed newvalue" | "str cvarname|bool newvalue', type: type.Function },
  { name: "SetCVarString", description: "str cvarname|str newvalue", type: type.Function },
  { name: "SetFloorTrigger", description: "int tag|int height|int special|[int arg1]|[int arg2]|[int arg3]|[int arg4]|[int arg5]", type: type.Function },
  { name: "SetFogDensity", description: "int tag|int amount", type: type.Function },
  { name: "SetFont", description: "str fontlump", type: type.Function },
  { name: "SetGravity", description: "fixed amount", type: type.Function },
  { name: "SetHUDClipRect", description: "int x|int y|int width|int height|[int wrapwidth]|[bool aspectratio]", type: type.Function },
  { name: "SetHUDSize", description: "int width|int height|bool statusbar", type: type.Function },
  { name: "SetHUDWrapWidth", description: "int wrapwidth", type: type.Function },
  { name: "SetLineActivation", description: "int lineid|int activation", type: type.Function },
  { name: "SetLineBlocking", description: "int lineid|int setting", type: type.Function },
  { name: "SetLineMonsterBlocking", description: "int lineid|int setting", type: type.Function },
  { name: "SetLineSpecial", description: "int lineid|int special|[int arg1]|[int arg2]|[int arg3]|[int arg4]|[int arg5]", type: type.Function },
  { name: "SetLineTexture", description: "int lineid|int line_side|int sidedef_texture|str texturename", type: type.Function },
  { name: "SetMarineSprite", description: "int tid|str actorclass", type: type.Function },
  { name: "SetMarineWeapon", description: "int tid|int weapon", type: type.Function },
  { name: "SetMugShotState", description: "str state", type: type.Function },
  { name: "SetMusic", description: "str song|[int order]", type: type.Function },
  { name: "SetMusicVolume", description: "fixed volume", type: type.Function },
  { name: "SetPointer", description: "int assign_slot|int tid|[int pointer_selector]|[int flags]", type: type.Function },
  { name: "SetResultValue", description: "int value", type: type.Function },
  { name: "SetSectorDamage", description: "int tag|int amount|[str damagetype]|[int interval]|[int leaky]", type: type.Function },
  { name: "SetSectorGlow", description: "int tag|bool which|int red|int green|int blue|int height", type: type.Function },
  { name: "SetSectorTerrain", description: "int tag|int whichplane|str terraintype", type: type.Function },
  { name: "SetSkyScrollSpeed", description: "int sky|float skyspeed", type: type.Function },
  { name: "SetSubtitleNumber", description: "int num|str sound", type: type.Function },
  { name: "SetThingSpecial", description: "int tid|int special|[int arg1]|[int arg2]|[int arg3]|[int arg4]|[int arg5]", type: type.Function },
  { name: "SetTranslation", description: "int tid|str transname", type: type.Function },
  { name: "SetUserArray", description: "int tid|str name|int pos|int value", type: type.Function },
  { name: "SetUserCVar", description: 'int playernum|str cvarname|int newvalue" | "int playernum|str cvarname|fixed newvalue" | "int playernum|str cvarname|bool newvalue', type: type.Function },
  { name: "SetUserCVarString", description: "int playernum|str cvarname|str newvalue", type: type.Function },
  { name: "SetUserVariable", description: "int tid|str name|int value", type: type.Function },
  { name: "SetWeapon", description: "str weaponname", type: type.Function },
  { name: "Sin", description: "int angle", type: type.Function },
  { name: "SoundSequence", description: "str sndseq", type: type.Function },
  { name: "SoundSequenceOnActor", description: "int tid|str sndseq", type: type.Function },
  { name: "SoundSequenceOnPolyobj", description: "int polynum|str sndseq", type: type.Function },
  { name: "SoundSequenceOnSector", description: "int tag|string seqname|int location", type: type.Function },
  { name: "SoundVolume", description: "int tid|int channel|fixed volume", type: type.Function },
  { name: "Spawn", description: "str classname|fixed x|fixed y|fixed z|[int tid]|[int angle]", type: type.Function },
  { name: "SpawnDecal", description: "int tid|str decalname|[int flags]|[fixed angle]|[fixed zoffset]|[fixed distance]", type: type.Function },
  { name: "SpawnForced", description: "str classname|fixed x|fixed y|fixed z|[int tid]|[int angle]", type: type.Function },
  { name: "SpawnParticle", description: "int color|[bool fullbright]|[int lifetime]|[int size]|[fixed x]|[fixed y]|[fixed z]|[fixed velx]|[fixed vely]|[fixed velz]|[fixed accelx]|[fixed accely]|[fixed accelz]|[int startalpha]|[int fadestep]|[fixed endsize]", type: type.Function },
  { name: "SpawnProjectile", description: "int tid|string type|int angle|int speed|int vspeed|int gravity|int newtid", type: type.Function },
  { name: "SpawnSpot", description: "str classname|int spottid|[int tid]|[int angle]", type: type.Function },
  { name: "SpawnSpotFacing", description: "str classname|int spottid|[int tid]", type: type.Function },
  { name: "SpawnSpotFacingForced", description: "str classname|int spottid|[int tid]", type: type.Function },
  { name: "SpawnSpotForced", description: "str classname|int spottid|[int tid]|[int angle]", type: type.Function },
  { name: "Sqrt", description: "int number", type: type.Function },
  { name: "StartSlideshow", description: "unknown parameter list", type: type.Function },
  { name: "StopSound", description: "int tid|[int channel]", type: type.Function },
  { name: "StrArg", description: "unknown parameter list", type: type.Function },
  { name: "StrCaseCmp", description: "str string1|str string2|[int maxcomparenum]", type: type.Function },
  { name: "StrCmp", description: "str string1|str string2|[int maxcomparenum]", type: type.Function },
  { name: "StrCpy", description: "a:destination|string source|[int source_index]", type: type.Function },
  { name: "StrIcmp", description: "str string1|str string2|[int maxcomparenum]", type: type.Function },
  { name: "StrLeft", description: "str string|int length", type: type.Function },
  { name: "StrLen", description: "str string", type: type.Function },
  { name: "StrMid", description: "str string|int start|int length", type: type.Function },
  { name: "StrParam", description: "type:expression", type: type.Function },
  { name: "StrRight", description: "str string|int length", type: type.Function },
  { name: "SwapActorTeleFog", description: "int tid", type: type.Function },
  { name: "TagWait", description: "int tag", type: type.Function },
  { name: "TakeActorInventory", description: "int tid|str inventory_item|int amount", type: type.Function },
  { name: "TakeInventory", description: "str inventory_item|int amount", type: type.Function },
  { name: "Thing_Damage2", description: "int tid|int amount|str type", type: type.Function },
  { name: "Thing_Projectile2", description: "int tid|int type|int angle|int speed|int vspeed|int gravity|int newtid", type: type.Function },
  { name: "ThingCount", description: "int type|int tid", type: type.Function },
  { name: "ThingCountName", description: "str classname|int tid", type: type.Function },
  { name: "ThingCountNameSector", description: "str classname|int tid|int tag", type: type.Function },
  { name: "ThingCountSector", description: "int type|int tid|int tag", type: type.Function },
  { name: "ThingSound", description: "int tid|str sound|int volume", type: type.Function },
  { name: "Timer", type: type.Function },
  { name: "UniqueTID", description: "[int tid]|[int limit]", type: type.Function },
  { name: "UnMorphActor", description: "int tid|[bool force]", type: type.Function },
  { name: "UseActorInventory", description: "int TID|str classname", type: type.Function },
  { name: "UseInventory", description: "str classname", type: type.Function },
  { name: "VectorAngle", description: "int x|int y", type: type.Function },
  { name: "VectorLength", description: "int x|int y", type: type.Function },
  { name: "Warp", description: "int tid|fixed xofs|fixed yofs|fixed zofs|fixed angle|int flags|[str success_state]|[bool exact]|[fixed heightoffset]|[fixed radiusoffset]|[fixed pitch]", type: type.Function },

  { name: "Player_GiveItem", description: "unknown parameters list", type: type.Function },
  { name: "Player_RemoveItem", description: "unknown parameters list", type: type.Function },
  { name: "Player_SetTeam", description: "int team", type: type.Function },
  { name: "Team_GivePoints", description: "int team|int points|int announce", type: type.Function },
  { name: "Team_Score", description: "int points|int nogrin", type: type.Function },

  { name: "AnnouncerSound", description: "str sound|int flags", type: type.Function },
  { name: "BeginDBTransaction", type: type.Function },
  { name: "BlueCount", type: type.Function },
  { name: "BlueScore", type: type.Function },
  { name: "BlueTeamCount", type: type.Function },
  { name: "BlueTeamScore", type: type.Function },
  { name: "ConsoleCommand", description: "str command", type: type.Function },
  { name: "ConsolePlayerNumber", type: type.Function },
  { name: "CountDBResults", description: "unknown parameters list", type: type.Function },
  { name: "EndDBTransaction", type: type.Function },
  { name: "FreeDBResults", description: "unknown parameters list", type: type.Function },
  { name: "GetDBEntries", description: "unknown parameters list", type: type.Function },
  { name: "GetDBEntry", description: "str table|str variable", type: type.Function },
  { name: "GetDBEntryRank", description: "unknown parameters list", type: type.Function },
  { name: "GetDBEntryString", description: "unknown parameters list", type: type.Function },
  { name: "GetDBResultKeyString", description: "unknown parameters list", type: type.Function },
  { name: "GetDBResultValue", description: "unknown parameters list", type: type.Function },
  { name: "GetDBResultValueString", description: "unknown parameters list", type: type.Function },
  { name: "GetGamemodeState", type: type.Function },
  { name: "GetInvasionState", type: type.Function },
  { name: "GetInvasionWave", type: type.Function },
  { name: "GetPlayerAccountName", description: "unknown parameters list", type: type.Function },
  { name: "GetPlayerLivesLeft", description: "int player", type: type.Function },
  { name: "GetTeamProperty", description: "int team|int property", type: type.Function },
  { name: "GetTimeProperty", description: "int timestamp|int which|[int utc]", type: type.Function },
  { name: "IncrementDBEntry", description: "unknown parameters list", type: type.Function },

  { name: "IsMultiplayer", description: "Checks if the game is currently a multiplayer game.", type: type.Function },

  { name: "IsNetworkGame", type: type.Function },
  { name: "IsOneFlagCTF", type: type.Function },
  { name: "KickFromGame", description: "int player|str reason", type: type.Function },
  { name: "Music_Change", description: "str music|int pattern", type: type.Function },
  { name: "NamedRequestScriptPuke", description: "str script|[int arg0]|[int arg1]|[int arg2]|[int arg3]", type: type.Function },
  { name: "PlayerArmorPoints", type: type.Function },
  { name: "PlayerHealth", type: type.Function },
  { name: "PlayerIsLoggedIn", description: "int playernumber", type: type.Function },
  { name: "PlayerIsSpectator", description: "int player", type: type.Function },
  { name: "PlayerTeam", type: type.Function },
  { name: "RedCount", type: type.Function },
  { name: "RedScore", type: type.Function },
  { name: "RedTeamCount", type: type.Function },
  { name: "RedTeamScore", type: type.Function },
  { name: "RequestScriptPuke", description: "int script|int arg0|int arg1|int arg2", type: type.Function },
  { name: "ResetMap", type: type.Function },
  { name: "SetActivatorToPlayer", description: "int playernumber", docs: "A replacement solution for AAPTR_PLAYERx that works with all 64 players instead of only 8", type: type.Function },
  { name: "SetDBEntry", description: "str table|str variable|int value", type: type.Function },
  { name: "SetDBEntryString", description: "unknown parameters list", type: type.Function },
  { name: "SetDeadSpectator", description: "int playernumber|int deadspectator", docs: "Turn alive players into dead spectators (deadspectator == 1) and revive dead spectators (deadspectator == 0)", type: type.Function },
  { name: "SetPlayerLivesLeft", description: "int player|int amount", type: type.Function },
  { name: "SinglePlayer", type: type.Function },
  { name: "SortDBEntries", description: "unknown parameters list", type: type.Function },
  { name: "Strftime", description: "int timestamp|str format|[int utc]", type: type.Function },
  { name: "SystemTime", type: type.Function },

  { name: "GetTeamScore", description: "int team", type: type.Function },
  { name: "SetTeamScore", description: "int team|int score", type: type.Function },
] as ICompletionTree[];