/**
 * Copyright (c) 2022 PROPHESSOR
 * 
 * This software is released under the MIT License.
 * https://opensource.org/licenses/MIT
 */

import { CompletionItemKind } from "vscode";
import { explodeString, ICompletionTree } from "../utils";

const type = CompletionItemKind;

function mapSladeDescription(name: string, description?: string) {
  if (!description) return;

  const desc = description
    // Map hudmessage-like "type; CONSTANT"
    .replace(/(.+?)\|;/g, '$1;')
    // Map args
    .replace(/\|(?!;)/g, ', ')
    // Map optional args (add "?" to the end)
    .replace(/\[(.+?)\]/g, '$1?');

  return `${name} (${desc})`;
}

function mapSladeSnippet(name: string, description?: string) {
  if (!description) return;

  let i = 1;

  const desc = description
    // Map first args (before "|") [+some dirty hack for "|;" in hudmessage]
    .replace(/(.+?)[|](;)?/g, (_, d, e) => `\${${i++}:${d}}${e ? '; ' : ', '}`)
    // Map last arg (after "|")
    .replace(/, ([^,]+)$/g, (_, d) => `, \${${i++}:${d}}`)
    // Map optional args (add "?" to the end)
    .replace(/\[(.+?)\]/g, (_, d) => `\${${i++}:${d}?}`);

  return `${name}(${desc})`;
}

function mapFunction(name: string, description?: string, docs?: string): ICompletionTree {
  return {
    name,
    description: mapSladeDescription(name, description),
    docs,
    insertText: mapSladeSnippet(name, description),
    type: type.Function,
  }
}

function genFunction(name: string, description?: string | string[], docs?: string): ICompletionTree[] {
  return Array.isArray(description)
    ? description.map(desc => mapFunction(name, desc, docs))
    : [mapFunction(name, description, docs)];
}

export default [
  ...explodeString(type.Function, "ForceField|Teleport_EndGameActivatorTID|CancelFade|ClearInventory|ClearLineSpecial|GameSkill|GameType|GetLineRowOffset|GetScreenHeight|GetScreenWidth|GetSigilPieces|GetWeapon|LineSide"),

  ...genFunction("ACS_Execute", "int script|[int mapnum]|[int s_arg1]|[int s_arg2]|[int s_arg3]", "Executes the specified script. Only one copy of the script can be running at a time when started using this function."),
  ...genFunction("ACS_ExecuteAlways", "int script|[int mapnum]|[int arg1]|[int arg2]|[int arg3]", "Executes the specified script. Multiple copies of the script can be running at the same time when started using this function|however they can not be suspended or terminated."),
  ...genFunction("ACS_ExecuteWithResult", "int script|[int s_arg1]|[int s_arg2]|[int s_arg3]|[int s_arg4]", "Executes the specified script and returns the value set in the script by SetResultValue"),
  ...genFunction("ACS_LockedExecute", "int script|[int mapnum]|[int arg1]|[int arg2]|[int lock]", "Executes the specified script if the player has the right key. Displays the 'remote' locked message."),
  ...genFunction("ACS_LockedExecuteDoor", "int script|[int mapnum]|[int arg1]|[int arg2]|[int lock]", "Executes the specified script if the player has the right key. Displays the 'door' locked message."),
  ...genFunction("ACS_Suspend", "int script|[int mapnum]", "Suspends execution of the specified script. Use ACS_Execute or ACS_LockedExecute to resume the script."),
  ...genFunction("ACS_Terminate", "int script|[int mapnum]", "Terminates execution of the specified script."),
  ...genFunction("Autosave", "", "Automatically saves the game to an autosave slot."),
  ...genFunction("Ceiling_CrushAndRaise", "int tag|int speed|int damage|[int crushmode]", ""),
  ...genFunction("Ceiling_CrushAndRaiseA", "int tag|int downspeed|int upspeed|int damage|[int crushmode]", ""),
  ...genFunction("Ceiling_CrushAndRaiseDist", "int tag|int dist|int speed|int damage|[int crushmode]", ""),
  ...genFunction("Ceiling_CrushAndRaiseSilentA", "int tag|int downspeed|int upspeed|int damage|[int crushmode]", ""),
  ...genFunction("Ceiling_CrushAndRaiseSilentDist", "int tag|int dist|int speed|int damage|[int crushmode]", ""),
  ...genFunction("Ceiling_CrushRaiseAndStay", "int tag|int speed|int damage|[int crushmode]", ""),
  ...genFunction("Ceiling_CrushRaiseAndStayA", "int tag|int downspeed|int upspeed|int damage|[int crushmode]", ""),
  ...genFunction("Ceiling_CrushRaiseAndStaySilA", "int tag|int downspeed|int upspeed|int damage|[int crushmode]", ""),
  ...genFunction("Ceiling_CrushStop", "int tag", ""),
  ...genFunction("Ceiling_LowerAndCrush", "int tag|int speed|int damage|[int crushmode]", ""),
  ...genFunction("Ceiling_LowerAndCrushDist", "int tag|int speed|int damage|int dist|[int crushmode]", ""),
  ...genFunction("Ceiling_LowerByTexture", "int tag|int speed|[int change]|[int damage]", ""),
  ...genFunction("Ceiling_LowerByValue", "int tag|int speed|int value", ""),
  ...genFunction("Ceiling_LowerByValueTimes8", "int tag|int speed|int value", ""),
  ...genFunction("Ceiling_LowerInstant", "int tag|int unused|int value", ""),
  ...genFunction("Ceiling_LowerToFloor", "int tag|int speed", ""),
  ...genFunction("Ceiling_LowerToHighestFloor", "int tag|int speed", ""),
  ...genFunction("Ceiling_LowerToLowest", "int tag|int speed", ""),
  ...genFunction("Ceiling_LowerToNearest", "int tag|int speed|[int change]|[int damage]", ""),
  ...genFunction("Ceiling_MoveToValue", "int tag|int speed|int value|int negative", ""),
  ...genFunction("Ceiling_MoveToValueAndCrush", "int tag|int speed|int value|int damage|[int crushmode]", ""),
  ...genFunction("Ceiling_MoveToValueTimes8", "int tag|int speed|int value|int negative", ""),
  ...genFunction("Ceiling_RaiseByTexture", "int tag|int speed|[int change]", ""),
  ...genFunction("Ceiling_RaiseByValue", "int tag|int speed|int value", ""),
  ...genFunction("Ceiling_RaiseByValueTimes8", "int tag|int speed|int value", ""),
  ...genFunction("Ceiling_RaiseInstant", "int tag|int unused|int value", ""),
  ...genFunction("Ceiling_RaiseToHighest", "int tag|int speed|[int change]", ""),
  ...genFunction("Ceiling_RaiseToHighestFloor", "int tag|int speed|[int change]", ""),
  ...genFunction("Ceiling_RaiseToLowest", "int tag|int speed|[int change]", ""),
  ...genFunction("Ceiling_RaiseToNearest", "int tag|int speed", ""),
  ...genFunction("Ceiling_Stop", "int tag", ""),
  ...genFunction("Ceiling_ToFloorInstant", "int tag|[int change]|[int damage]|[int gap]", ""),
  ...genFunction("Ceiling_ToHighestInstant", "int tag|[int change]|[int damage]", ""),
  ...genFunction("Ceiling_Waggle", "int tag|int amplitude|int frequency|int delay|int time", ""),
  ...genFunction("ChangeCamera", "int tid|int who|int revert", ""),
  ...genFunction("ChangeSkill", "int level", ""),
  ...genFunction("ClearForceField", "int tag", ""),
  ...genFunction("DamageThing", "int damage|[int mod]", ""),
  ...genFunction("Door_Animated", "int tag|int speed|int delay|int lock", ""),
  ...genFunction("Door_AnimatedClose", "int tag|int speed", ""),
  ...genFunction("Door_Close", "int tag|int speed|[int lighttag]", ""),
  ...genFunction("Door_CloseWaitOpen", "int tag|int speed|int delay|[int lighttag]", ""),
  ...genFunction("Door_LockedRaise", "int tag|int speed|int delay|int lock|[int lighttag]", ""),
  ...genFunction("Door_Open", "int tag|int speed|[int lighttag]", ""),
  ...genFunction("Door_Raise", "int tag|int speed|int delay|[int lighttag]", ""),
  ...genFunction("Door_WaitClose", "int tag|int speed|int wait|[int lighttag]", ""),
  ...genFunction("Door_WaitRaise", "int tag|int speed|int delay|int wait|[int lighttag]", ""),
  ...genFunction("Elevator_LowerToNearest", "int tag|int speed", ""),
  ...genFunction("Elevator_MoveToFloor", "int tag|int speed", ""),
  ...genFunction("Elevator_RaiseToNearest", "int tag|int speed", ""),
  ...genFunction("Exit_Normal", "int position", ""),
  ...genFunction("Exit_Secret", "int position", ""),
  ...genFunction("Floor_CrushStop", "int tag", ""),
  ...genFunction("Floor_Donut", "int pillartag|int pillarspeed|int moatspeed", ""),
  ...genFunction("Floor_LowerByTexture", "int tag|int speed|[int change]", ""),
  ...genFunction("Floor_LowerByValue", "int tag|int speed|int value", ""),
  ...genFunction("Floor_LowerByValueTimes8", "int tag|int speed|int value", ""),
  ...genFunction("Floor_LowerInstant", "int tag|int unused|int value", ""),
  ...genFunction("Floor_LowerToHighest", "int tag|int speed|int adjust|[int always]", ""),
  ...genFunction("Floor_LowerToHighestEE", "int tag|int speed|[int change]", ""),
  ...genFunction("Floor_LowerToLowest", "int tag|int speed", ""),
  ...genFunction("Floor_LowerToLowestCeiling", "int tag|int speed|[int change]", ""),
  ...genFunction("Floor_LowerToLowestTxTy", "int tag|int speed", ""),
  ...genFunction("Floor_LowerToNearest", "int tag|int speed", ""),
  ...genFunction("Floor_MoveToValue", "int tag|int speed|int value|int negative", ""),
  ...genFunction("Floor_MoveToValueAndCrush", "int tag|int speed|int value|int damage|[int crushmode]", ""),
  ...genFunction("Floor_MoveToValueTimes8", "int tag|int speed|int value|int negative", ""),
  ...genFunction("Floor_RaiseAndCrush", "int tag|int speed|int damage|[int crushmode]", ""),
  ...genFunction("Floor_RaiseAndCrushDoom", "int tag|int speed|int damage|[int crushmode]", ""),
  ...genFunction("Floor_RaiseByTexture", "int tag|int speed", ""),
  ...genFunction("Floor_RaiseByValue", "int tag|int speed|int value", ""),
  ...genFunction("Floor_RaiseByValueTimes8", "int tag|int speed|int value", ""),
  ...genFunction("Floor_RaiseByValueTxTy", "int tag|int speed|int value", ""),
  ...genFunction("Floor_RaiseInstant", "int tag|int unused|int value", ""),
  ...genFunction("Floor_RaiseToCeiling", "int tag|int speed|[int change]|[int damage]|[int gap]", ""),
  ...genFunction("Floor_RaiseToHighest", "int tag|int speed", ""),
  ...genFunction("Floor_RaiseToLowest", "int tag|int change|[int damage]", ""),
  ...genFunction("Floor_RaiseToLowestCeiling", "int tag|int speed", ""),
  ...genFunction("Floor_RaiseToNearest", "int tag|int speed", ""),
  ...genFunction("Floor_Stop", "int tag", ""),
  ...genFunction("Floor_ToCeilingInstant", "int tag|[int change]|[int damage]|[int gap]", ""),
  ...genFunction("Floor_TransferNumeric", "int tag", ""),
  ...genFunction("Floor_TransferTrigger", "int tag", ""),
  ...genFunction("Floor_Waggle", "int tag|int amp|int freq|int offset|int time", ""),
  ...genFunction("FloorAndCeiling_LowerByValue", "int tag|int speed|int value", ""),
  ...genFunction("FloorAndCeiling_LowerRaise", "int tag|int floor_speed|int ceiling_speed|[int boom1998]", ""),
  ...genFunction("FloorAndCeiling_RaiseByValue", "int tag|int speed|int value", ""),
  ...genFunction("FS_Execute", "int script|[int frontonly]|[int lock]|[int lockedmessage]", ""),
  ...genFunction("Generic_Ceiling", "int tag|int speed|int height|int target|int flags", ""),
  ...genFunction("Generic_Crusher", "int tag|int downspeed|int upspeed|int silent|int damage", ""),
  ...genFunction("Generic_Crusher2", "int tag|int downspeed|int upspeed|int silent|int damage", ""),
  ...genFunction("Generic_Door", "int tag|int speed|int kind|int delay|int lock", ""),
  ...genFunction("Generic_Floor", "int tag|int speed|int height|int target|int flags", ""),
  ...genFunction("Generic_Lift", "int tag|int speed|int delay|int target|int height", ""),
  ...genFunction("Generic_Stairs", "int tag|int speed|int step|int flags|int reset", ""),
  ...genFunction("GlassBreak", "[int nojunk]", ""),
  ...genFunction("HealThing", "amount|[int max]", ""),
  ...genFunction("Light_ChangeToValue", "int tag|int value", ""),
  ...genFunction("Light_Fade", "int tag|int value|int tics", ""),
  ...genFunction("Light_Flicker", "int tag|int upper|int lower", ""),
  ...genFunction("Light_ForceLightning", "int mode", ""),
  ...genFunction("Light_Glow", "int tag|int upper|int lower|int tics", ""),
  ...genFunction("Light_LowerByValue", "int tag|int value", ""),
  ...genFunction("Light_MaxNeighbor", "int tag", ""),
  ...genFunction("Light_MinNeighbor", "int tag", ""),
  ...genFunction("Light_RaiseByValue", "int tag|int value", ""),
  ...genFunction("Light_Stop", "int tag", ""),
  ...genFunction("Light_Strobe", "int tag|int upper|int lower|int u-tics|int l-tics", ""),
  ...genFunction("Light_StrobeDoom", "int tag|int u-tics|int l-tics", ""),
  ...genFunction("Line_AlignCeiling", "int lineid|int side", ""),
  ...genFunction("Line_AlignFloor", "int lineid|int side", ""),
  ...genFunction("Line_SetAutomapFlags", "int lineid|int setflags|int clearflags", ""),
  ...genFunction("Line_SetAutomapStyle", "int lineid|int style", ""),
  ...genFunction("Line_SetBlocking", "int lineid|int setflags|int clearflags", ""),
  ...genFunction("Line_SetHealth", "int lineid|int health", ""),
  ...genFunction("Line_SetPortalTarget", "int sourceline|int targetline", ""),
  ...genFunction("Line_SetTextureOffset", "int id|int x|int y|int side|int flags", ""),
  ...genFunction("Line_SetTextureScale", "int id|int x|int y|int side|int flags", ""),
  ...genFunction("NoiseAlert", "int target_tid|int emitter_tid", ""),
  ...genFunction("Pillar_Build", "int tag|int speed|int value", ""),
  ...genFunction("Pillar_BuildAndCrush", "int tag|int speed|int value|int damage|int crushmode", ""),
  ...genFunction("Pillar_Open", "int tag|int speed|int floor|int ceiling", ""),
  ...genFunction("Plat_DownByValue", "int tag|int speed|int delay|int value", ""),
  ...genFunction("Plat_DownWaitUpStay", "int tag|int speed|int delay", ""),
  ...genFunction("Plat_DownWaitUpStayLip", "int tag|int speed|int delay|int lip|int sound", ""),
  ...genFunction("Plat_PerpetualRaise", "int tag|int speed|int delay", ""),
  ...genFunction("Plat_PerpetualRaiseLip", "int tag|int speed|int delay|int lip", ""),
  ...genFunction("Plat_RaiseAndStayTx0", "int tag|int speed|[int lockout]", ""),
  ...genFunction("Plat_Stop", "int tag", ""),
  ...genFunction("Plat_ToggleCeiling", "int tag", ""),
  ...genFunction("Plat_UpByValue", "int tag|int speed|int delay|int value", ""),
  ...genFunction("Plat_UpByValueStayTx", "int tag|int speed|int value", ""),
  ...genFunction("Plat_UpNearestWaitDownStay", "int tag|int speed|int delay", ""),
  ...genFunction("Plat_UpWaitDownStay", "int tag|int speed|int delay", ""),
  ...genFunction("Polyobj_DoorSlide", "int po|int speed|int angle|int dist|int delay", ""),
  ...genFunction("Polyobj_DoorSwing", "int po|int speed|int angle|int delay", ""),
  ...genFunction("Polyobj_Move", "int po|int speed|int angle|int dist", ""),
  ...genFunction("Polyobj_MoveTimes8", "int po|int speed|int angle|int dist", ""),
  ...genFunction("Polyobj_MoveTo", "int po|int speed|int x|int y", ""),
  ...genFunction("Polyobj_MoveToSpot", "int po|int speed|int tid", ""),
  ...genFunction("Polyobj_OR_Move", "int po|int speed|int angle|int distance", ""),
  ...genFunction("Polyobj_OR_MoveTimes8", "int po|int speed|int angle|int distance", ""),
  ...genFunction("Polyobj_OR_MoveTo", "int po|int speed|int x|int y", ""),
  ...genFunction("Polyobj_OR_MoveToSpot", "int po|int speed|int tid", ""),
  ...genFunction("Polyobj_OR_RotateLeft", "int po|int speed|int angle", ""),
  ...genFunction("Polyobj_OR_RotateRight", "int po|int speed|int angle", ""),
  ...genFunction("Polyobj_RotateLeft", "int po|int speed|int angle", ""),
  ...genFunction("Polyobj_RotateRight", "int po|int speed|int angle", ""),
  ...genFunction("Polyobj_Stop", "int po", ""),
  ...genFunction("Polyobj_StopSound", "int po", ""),
  ...genFunction("Radius_Quake", "int intensity|int duration|int damrad|int tremrad|int tid", ""),
  ...genFunction("Scroll_Ceiling", "int tag|int x-move|int y-move|int unused", ""),
  ...genFunction("Scroll_Floor", "int tag|int x-move|int y-move|int mode", ""),
  ...genFunction("Scroll_Texture_Both", "int lineid|int left|int right|int up|int down", ""),
  ...genFunction("Scroll_Wall", "int lineid|int x|int y|int side|int flags", ""),
  ...genFunction("Sector_ChangeFlags", "int tag|int set|int clear", ""),
  ...genFunction("Sector_ChangeSound", "int tag|int newsequence", ""),
  ...genFunction("Sector_SetCeilingGlow", "int tag|int height|int red|int green|int blue", ""),
  ...genFunction("Sector_SetCeilingPanning", "int tag|int x-int|int x-frac|int y-int|int y-frac", ""),
  ...genFunction("Sector_SetCeilingScale", "int tag|int x-int|int x-frac|int y-int|int y-frac", ""),
  ...genFunction("Sector_SetCeilingScale2", "int tag|int x-factor|int y-factor", ""),
  ...genFunction("Sector_SetColor", "int tag|int r|int g|int b|int desaturate", ""),
  ...genFunction("Sector_SetCurrent", "int tag|int amount|int angle|int useline", ""),
  ...genFunction("Sector_SetDamage", "int tag|int amount|int mod|int interval|int leaky", ""),
  ...genFunction("Sector_SetFade", "int tag|int r|int g|int b", ""),
  ...genFunction("Sector_SetFloorGlow", "int tag|int height|int red|int green|int blue", ""),
  ...genFunction("Sector_SetFloorPanning", "int tag|int x-int|int x-frac|int y-int|int y-frac", ""),
  ...genFunction("Sector_SetFloorScale", "int tag|int x-int|int x-frac|int y-int|int y-frac", ""),
  ...genFunction("Sector_SetFloorScale2", "int tag|int x-factor|int y-factor", ""),
  ...genFunction("Sector_SetFriction", "int tag|int amount", ""),
  ...genFunction("Sector_SetGravity", "int tag|int intpart|int fracpart", ""),
  ...genFunction("Sector_SetHealth", "int tag|int part|int health", ""),
  ...genFunction("Sector_SetLink", "int controltag|int linktag|int floor/ceiling|int movetype", ""),
  ...genFunction("Sector_SetPlaneReflection", "int tag|int floor|int ceiling", ""),
  ...genFunction("Sector_SetRotation", "int tag|int floor-angle|int ceiling-angle", ""),
  ...genFunction("Sector_SetTranslucent", "int tag|int plane|int amount|int type", ""),
  ...genFunction("Sector_SetWind", "int tag|int amount|int angle|int useline", ""),
  ...genFunction("SendToCommunicator", "int voc_num|int front-only|int identify|int nolog", ""),
  ...genFunction("SetGlobalFogParameter", "int type|int value", ""),
  ...genFunction("SetPlayerProperty", "int allplayers|int value|int which", ""),
  ...genFunction("Stairs_BuildDown", "int tag|int speed|int height|int delay|int reset", ""),
  ...genFunction("Stairs_BuildDownDoom", "int tag|int speed|int height|int delay|int reset", ""),
  ...genFunction("Stairs_BuildDownDoomSync", "int tag|int speed|int height|int reset", ""),
  ...genFunction("Stairs_BuildDownSync", "int tag|int speed|int height|int reset", ""),
  ...genFunction("Stairs_BuildUp", "int tag|int speed|int height|int delay|int reset", ""),
  ...genFunction("Stairs_BuildUpDoom", "int tag|int speed|int height|int delay|int reset", ""),
  ...genFunction("Stairs_BuildUpDoomCrush", "int tag|int speed|int height|int delay|int reset", ""),
  ...genFunction("Stairs_BuildUpDoomSync", "int tag|int speed|int height|int reset", ""),
  ...genFunction("Stairs_BuildUpSync", "int tag|int speed|int height|int reset", ""),
  ...genFunction("StartConversation", "int tid|[int facetalker]", ""),
  ...genFunction("Teleport", "int tid|int tag|int nosourcefog", ""),
  ...genFunction("Teleport_Line", "int thisid|int destid|[int reversed]", ""),
  ...genFunction("Teleport_NewMap", "int map|int pos|[int keepangle]", ""),
  ...genFunction("Teleport_NoFog", "int tid|[int useang]|[int sectortag]|[int keepheight]", ""),
  ...genFunction("Teleport_NoStop", "int tid|int sectortag|[int nosourcefog]", ""),
  ...genFunction("Teleport_ZombieChanger", "int tid|int sectortag", ""),
  ...genFunction("TeleportGroup", "int group_tid|int source_tid|int dest_tid|int move_source|int use_fog", ""),
  ...genFunction("TeleportInSector", "int tag|int source_tid|int dest_tid|int use_fog|[int group_tid]", ""),
  ...genFunction("TeleportOther", "int other_tid|int dest_tid|[int fog]", ""),
  ...genFunction("Thing_Activate", "int tid", ""),
  ...genFunction("Thing_ChangeTID", "int oldtid|int newtid", ""),
  ...genFunction("Thing_Damage", "int tid|int amount|int mod", ""),
  ...genFunction("Thing_Deactivate", "int tid", ""),
  ...genFunction("Thing_Destroy", "int tid|[int extreme]|[int sector_tag]", ""),
  ...genFunction("Thing_Hate", "int hater|int hatee|[int flags]", ""),
  ...genFunction("Thing_Move", "int tid|int mapspot|[int nofog]", ""),
  ...genFunction("Thing_Projectile", "int tid|int type|int angle|int speed|int vspeed", ""),
  ...genFunction("Thing_ProjectileAimed", "int tid|int type|int speed|int target|[int newtid]", ""),
  ...genFunction("Thing_ProjectileGravity", "int tid|int type|int angle|int speed|int vspeed", ""),
  ...genFunction("Thing_ProjectileIntercept", "int tid|int type|int speed|int target|int newtid", ""),
  ...genFunction("Thing_Raise", "int tid", ""),
  ...genFunction("Thing_Remove", "int tid", ""),
  ...genFunction("Thing_SetConversation", "int tid|conv_id", ""),
  ...genFunction("Thing_SetGoal", "int tid|int goal|int delay|[int chasegoal]", ""),
  ...genFunction("Thing_SetSpecial", "int tid|int special|int arg1|int arg2|int arg3", ""),
  ...genFunction("Thing_SetTranslation", "int tid|int translation_num", ""),
  ...genFunction("Thing_Spawn", "int tid|int type|int angle|[int newtid]", ""),
  ...genFunction("Thing_SpawnFacing", "int tid|int type|[int nofog]|[int newtid]", ""),
  ...genFunction("Thing_SpawnNoFog", "int tid|int type|int angle|[int newtid]", ""),
  ...genFunction("Thing_Stop", "int tid", ""),
  ...genFunction("ThrustThing", "int angle|int force|[int limit]|[int tid]", ""),
  ...genFunction("ThrustThingZ", "int tid|int zthrust|int dir|int set", ""),
  ...genFunction("TranslucentLine", "int id|int amount|int transtype", ""),
  ...genFunction("UsePuzzleItem", "int item|int script", ""),
  ...genFunction("ACS_ExecuteWait", "int script|int unused|int arg1|int arg2|int arg3", ""),
  ...genFunction("ACS_NamedExecute", "str script|[int mapnum]|[int s_arg1]|[int s_arg2]|[int s_arg3]", ""),
  ...genFunction("ACS_NamedExecuteAlways", "str script|[int mapnum]|[int arg1]|[int arg2]|[int arg3]", ""),
  ...genFunction("ACS_NamedExecuteWait", "str script|int unused|int arg1|int arg2|int arg3", ""),
  ...genFunction("ACS_NamedExecuteWithResult", "str script|[int s_arg1]|[int s_arg2]|[int s_arg3]|[int s_arg4]", ""),
  ...genFunction("ACS_NamedLockedExecute", "str script|[int mapnum]|[int arg1]|[int arg2]|[int lock]", ""),
  ...genFunction("ACS_NamedLockedExecuteDoor", "str script|[int mapnum]|[int arg1]|[int arg2]|[int lock]", ""),
  ...genFunction("ACS_NamedSuspend", "str script|[int mapnum]", ""),
  ...genFunction("ACS_NamedTerminate", "str script|[int mapnum]", ""),
  ...genFunction("ActivatorSound", "str sound|int volume", ""),
  ...genFunction("AmbientSound", "str sound|int volume", ""),
  ...genFunction("CanRaiseActor", "int tid", ""),
  ...genFunction("Ceil", "fixed value", ""),
  ...genFunction("ChangeActorAngle", "int tid|fixed angle|[bool interpolate]", ""),
  ...genFunction("ChangeActorPitch", "int tid|fixed pitch|[bool interpolate]", ""),
  ...genFunction("ChangeActorRoll", "int tid|fixed angle|[bool interpolate]", ""),
  ...genFunction("ChangeCeiling", "int tag|str flatname", ""),
  ...genFunction("ChangeFloor", "int tag|str flatname", ""),
  ...genFunction("ChangeLevel", "str mapname|int position|int flags,[ int skill]", ""),
  ...genFunction("ChangeSky", "str sky1|str sky2", ""),
  ...genFunction("CheckActorCeilingTexture", "int tid|str texture", ""),
  ...genFunction("CheckActorClass", "int tid|str class", ""),
  ...genFunction("CheckActorFloorTexture", "int tid|str texture", ""),
  ...genFunction("CheckActorInventory", "int tid|str inventory_item", ""),
  ...genFunction("CheckActorProperty", ["int tid|int property|int value", "int tid|int property|float value", "int tid|int property|str value"], ""),
  ...genFunction("CheckActorState", "int tid|str statename|[bool exact]", ""),
  ...genFunction("CheckClass", "str classname", ""),
  ...genFunction("CheckFlag", "int tid|str flag", ""),
  ...genFunction("CheckFont", "str fontname", ""),
  ...genFunction("CheckInventory", "str inventory_item", ""),
  ...genFunction("CheckPlayerCamera", "int player", ""),
  ...genFunction("CheckProximity", "int tid|str classname|fixed distance|[int count]|[int flags]|[int pointer]", ""),
  ...genFunction("CheckSight", "int source|int dest|[int flags]", ""),
  ...genFunction("CheckWeapon", "str weapon", ""),
  ...genFunction("ClassifyActor", "int tid", ""),
  ...genFunction("ClearActorInventory", "int tid", ""),
  ...genFunction("Cos", "int angle", ""),
  ...genFunction("CreateTranslation", ["int transnumber|a:b=c:d|...", "int transnumber|a:b=[red1,green1,blue1]:[red2,green2,blue2]|..."], ""),
  ...genFunction("DamageActor", "int target_tid|int target_pointer|int inflictor_tid|int inflictor_pointer|int amount|str damagetype", ""),
  ...genFunction("Delay", "int tics", ""),
  ...genFunction("DropInventory", "int tid|str item", ""),
  ...genFunction("DropItem", "int tid|str item|[int dropamount]|[int chance]", ""),
  ...genFunction("FadeRange", "int red1|int green1|int blue1|fixed amount1|int red2|int green2|int blue2|fixed amount2|fixed seconds", ""),
  ...genFunction("FadeTo", "int red|int green|int blue|fixed amount|fixed seconds", ""),
  ...genFunction("FixedDiv", "fixed a|fixed b", ""),
  ...genFunction("FixedMul", "fixed a|fixed b", ""),
  ...genFunction("FixedSqrt", "fixed number", ""),
  ...genFunction("Floor", "fixed value", ""),
  ...genFunction("GetActorAngle", "int tid", ""),
  ...genFunction("GetActorCeilingZ", "int tid", ""),
  ...genFunction("GetActorClass", "int tid", ""),
  ...genFunction("GetActorFloorTerrain", "int tid", ""),
  ...genFunction("GetActorFloorTexture", "int tid", ""),
  ...genFunction("GetActorFloorZ", "int tid", ""),
  ...genFunction("GetActorLightLevel", "int tid", ""),
  ...genFunction("GetActorPitch", "int tid", ""),
  ...genFunction("GetActorPowerupTics", "int tid|str powerup", ""),
  ...genFunction("GetActorProperty", "int tid|int property", ""),
  ...genFunction("GetActorRoll", "int tid", ""),
  ...genFunction("GetActorVelX", "int tid", ""),
  ...genFunction("GetActorVelY", "int tid", ""),
  ...genFunction("GetActorVelZ", "int tid", ""),
  ...genFunction("GetActorViewHeight", "int tid", ""),
  ...genFunction("GetActorX", "int tid", ""),
  ...genFunction("GetActorY", "int tid", ""),
  ...genFunction("GetActorZ", "int tid", ""),
  ...genFunction("GetAirSupply", "int playernum", ""),
  ...genFunction("GetAmmoCapacity", "str classname", ""),
  ...genFunction("GetArmorInfo", "int infotype", ""),
  ...genFunction("GetArmorType", "string armortype|int playernum", ""),
  ...genFunction("GetChar", "str string|int index", ""),
  ...genFunction("GetCVar", "str cvar", ""),
  ...genFunction("GetCVarString", "str cvarname", ""),
  ...genFunction("GetLevelInfo", "int levelinfo", ""),
  ...genFunction("GetLineActivation", "int lineid", ""),
  ...genFunction("GetLineHealth", "int lineid", ""),
  ...genFunction("GetLineUDMFFixed", "int lineid|str key", ""),
  ...genFunction("GetLineUDMFInt", "int lineid|str key", ""),
  ...genFunction("GetLineX", "unknown parameter list", ""),
  ...genFunction("GetLineY", "unknown parameter list", ""),
  ...genFunction("GetMaxInventory", "int tid|str inventory", ""),
  ...genFunction("GetPlayerInfo", "int playernumber|int playerinfo", ""),
  ...genFunction("GetPlayerInput", "int player|int input", ""),
  ...genFunction("GetPolyobjX", "int polynum", ""),
  ...genFunction("GetPolyobjY", "int polynum", ""),
  ...genFunction("GetSectorCeilingZ", "int tag|int x|int y", ""),
  ...genFunction("GetSectorFloorZ", "int tag|int x|int y", ""),
  ...genFunction("GetSectorHealth", "int tag|int part", ""),
  ...genFunction("GetSectorLightLevel", "int tag", ""),
  ...genFunction("GetSectorUDMFFixed", "int tag|string key", ""),
  ...genFunction("GetSectorUDMFInt", "int tag|string key", ""),
  ...genFunction("GetSideUDMFFixed", "int lineid|bool back|string key", ""),
  ...genFunction("GetSideUDMFInt", "int lineid|bool back|string key", ""),
  ...genFunction("GetThingUDMFFixed", "int tid|string key", ""),
  ...genFunction("GetThingUDMFInt", "int tid|string key", ""),
  ...genFunction("GetUserArray", "int tid|str name|int pos", ""),
  ...genFunction("GetUserCVar", "int playernum|str cvarname", ""),
  ...genFunction("GetUserCVarString", "int playernum|str cvarname", ""),
  ...genFunction("GetUserVariable", "int tid|str name", ""),
  ...genFunction("GiveActorInventory", "int tid|str inventory_item|int amount", ""),
  ...genFunction("GiveInventory", "str inventory_item|int amount", ""),
  ...genFunction("HudMessage", ["type:expression...|; int type|int id|int color|fixed x|fixed y|fixed holdTime|fixed alpha", "type:expression...|; HUDMSG_FADEOUT|int id|int color|fixed x|fixed y|fixed holdTime|fixed fadetime|fixed alpha", "type:expression...|; HUDMSG_TYPEON|int id|int color|fixed x|fixed y|fixed holdTime|fixed typetime|fixed fadetime|fixed alpha", "type:expression...|; HUDMSG_FADEINOUT|int id|int color|fixed x|fixed y|fixed holdTime|fixed inTime|fixed outTime|fixed alpha"], ""),
  ...genFunction("HudMessageBold", ["type:expression...|; int type|int id|int color|fixed x|fixed y|fixed holdTime|fixed alpha", "type:expression...|; HUDMSG_FADEOUT|int id|int color|fixed x|fixed y|fixed holdTime|fixed fadetime|fixed alpha", "type:expression...|; HUDMSG_TYPEON|int id|int color|fixed x|fixed y|fixed holdTime|fixed typetime|fixed fadetime|fixed alpha", "type:expression...|; HUDMSG_FADEINOUT|int id|int color|fixed x|fixed y|fixed holdTime|fixed inTime|fixed outTime|fixed alpha"], ""),
  ...genFunction("IsPointerEqual", "int ptr_select1|int ptr_select2|[int tid1]|[int tid2]", ""),
  ...genFunction("IsTIDUsed", "int tid", ""),
  ...genFunction("LineAttack", "int tid|fixed angle|fixed pitch|int damage|[str pufftype]|[str damagetype]|[fixed range]|[int flags]|[int pufftid]", ""),
  ...genFunction("LocalAmbientSound", "str sound|int volume", ""),
  ...genFunction("LocalSetMusic", "str song|[int order]", ""),
  ...genFunction("Log", "type:expression", ""),
  ...genFunction("MorphActor", "int tid|[str playerclass]|[str monsterclass]|[int duration]|[int style]|[str morphflash]|[str unmorphflash]", ""),
  ...genFunction("NamedScriptWait", "str script", ""),
  ...genFunction("PickActor", "int source_tid|fixed angle|fixed pitch|fixed distance|int new_tid|[int actor_mask]|[int wall_mask]|[int flags]", ""),
  ...genFunction("PlayActorSound", "int tid|int sound|[int channel]|[fixed volume]|[bool looping]|[fixed attenuation]", ""),
  ...genFunction("PlayerClass", "int playernumber", ""),
  ...genFunction("PlayerCount", "", ""),
  ...genFunction("PlayerFrags", "", ""),
  ...genFunction("PlayerInGame", "int playernumber", ""),
  ...genFunction("PlayerIsBot", "int playernumber", ""),
  ...genFunction("PlayerNumber", "", ""),
  ...genFunction("PlayMovie", "str moviename - but this function does not work anyway", ""),
  ...genFunction("PlaySound", "int tid|str sound|[int channel]|[fixed volume]|[bool looping]|[fixed attenuation]|[bool local]", ""),
  ...genFunction("PolyWait", "int polynum", ""),
  ...genFunction("Print", "type:expression", ""),
  ...genFunction("PrintBold", "type:expression", ""),
  ...genFunction("QuakeEx", "int tid|int intensityX|int intensityY|int intensityZ|int duration|int damrad|int tremrad|sound sfx|[int flags]|[fixed mulWaveX]|[fixed mulWaveY]|[fixed mulWaveZ]|[int falloff]|[int highpoint]|[fixed rollIntensity]|[fixed rollWave]", ""),
  ...genFunction("Radius_Quake2", "int tid|int intensity|int duration|int damrad|int tremrad|str sound", ""),
  ...genFunction("Random", "int min|int max", ""),
  ...genFunction("ReplaceTextures", "str oldtexturename|str newtexturename|[int flags]", ""),
  ...genFunction("Round", "fixed value", ""),
  ...genFunction("ScriptCall", "str classname|str funcname|args", ""),
  ...genFunction("ScriptWait", "int script", ""),
  ...genFunction("SectorDamage", "int tag|int amount|str type|str protection_item|int flags", ""),
  ...genFunction("SectorSound", "str sound|int volume", ""),
  ...genFunction("SetActivator", "int tid|[int pointer_selector]", ""),
  ...genFunction("SetActivatorToTarget", "int tid", ""),
  ...genFunction("SetActorAngle", "int tid|fixed angle", ""),
  ...genFunction("SetActorFlag", "int tid|str flagname|bool set", ""),
  ...genFunction("SetActorPitch", "int tid|fixed pitch", ""),
  ...genFunction("SetActorPosition", "int tid|fixed x|fixed y|fixed z|bool fog", ""),
  ...genFunction("SetActorProperty", ["int tid|int property|int value", "int tid|int property|float value", "int tid|int property|str value"], ""),
  ...genFunction("SetActorRoll", "int tid|fixed angle", ""),
  ...genFunction("SetActorState", "int tid|str statename|[bool exact]", ""),
  ...genFunction("SetActorTeleFog", "int tid|str sourcefog|str destfog", ""),
  ...genFunction("SetActorVelocity", "int tid|fixed velx|fixed vely|fixed velz|bool add|bool setbob", ""),
  ...genFunction("SetAirControl", "int amount", ""),
  ...genFunction("SetAirSupply", "int playernum|int tics", ""),
  ...genFunction("SetAmmoCapacity", "str typename|int maxamount", ""),
  ...genFunction("SetCameraToTexture", "int cameratid|str texturename|int fov", ""),
  ...genFunction("SetCeilingTrigger", "int tag|int height|int special|[int arg1]|[int arg2]|[int arg3]|[int arg4]|[int arg5]", ""),
  ...genFunction("SetCVar", ["str cvarname|int newvalue", "str cvarname|fixed newvalue", "str cvarname|bool newvalue"], ""),
  ...genFunction("SetCVarString", "str cvarname|str newvalue", ""),
  ...genFunction("SetFloorTrigger", "int tag|int height|int special|[int arg1]|[int arg2]|[int arg3]|[int arg4]|[int arg5]", ""),
  ...genFunction("SetFogDensity", "int tag|int amount", ""),
  ...genFunction("SetFont", "str fontlump", ""),
  ...genFunction("SetGravity", "fixed amount", ""),
  ...genFunction("SetHUDClipRect", "int x|int y|int width|int height|[int wrapwidth]|[bool aspectratio]", ""),
  ...genFunction("SetHUDSize", "int width|int height|bool statusbar", ""),
  ...genFunction("SetHUDWrapWidth", "int wrapwidth", ""),
  ...genFunction("SetLineActivation", "int lineid|int activation", ""),
  ...genFunction("SetLineBlocking", "int lineid|int setting", ""),
  ...genFunction("SetLineMonsterBlocking", "int lineid|int setting", ""),
  ...genFunction("SetLineSpecial", "int lineid|int special|[int arg1]|[int arg2]|[int arg3]|[int arg4]|[int arg5]", ""),
  ...genFunction("SetLineTexture", "int lineid|int line_side|int sidedef_texture|str texturename", ""),
  ...genFunction("SetMarineSprite", "int tid|str actorclass", ""),
  ...genFunction("SetMarineWeapon", "int tid|int weapon", ""),
  ...genFunction("SetMugShotState", "str state", ""),
  ...genFunction("SetMusic", "str song|[int order]", ""),
  ...genFunction("SetMusicVolume", "fixed volume", ""),
  ...genFunction("SetPointer", "int assign_slot|int tid|[int pointer_selector]|[int flags]", ""),
  ...genFunction("SetResultValue", "int value", ""),
  ...genFunction("SetSectorDamage", "int tag|int amount|[str damagetype]|[int interval]|[int leaky]", ""),
  ...genFunction("SetSectorGlow", "int tag|bool which|int red|int green|int blue|int height", ""),
  ...genFunction("SetSectorTerrain", "int tag|int whichplane|str terraintype", ""),
  ...genFunction("SetSkyScrollSpeed", "int sky|float skyspeed", ""),
  ...genFunction("SetSubtitleNumber", "int num|str sound", ""),
  ...genFunction("SetThingSpecial", "int tid|int special|[int arg1]|[int arg2]|[int arg3]|[int arg4]|[int arg5]", ""),
  ...genFunction("SetTranslation", "int tid|str transname", ""),
  ...genFunction("SetUserArray", "int tid|str name|int pos|int value", ""),
  ...genFunction("SetUserCVar", ["int playernum|str cvarname|int newvalue", "int playernum|str cvarname|fixed newvalue", "int playernum|str cvarname|bool newvalue"], ""),
  ...genFunction("SetUserCVarString", "int playernum|str cvarname|str newvalue", ""),
  ...genFunction("SetUserVariable", "int tid|str name|int value", ""),
  ...genFunction("SetWeapon", "str weaponname", ""),
  ...genFunction("Sin", "int angle", ""),
  ...genFunction("SoundSequence", "str sndseq", ""),
  ...genFunction("SoundSequenceOnActor", "int tid|str sndseq", ""),
  ...genFunction("SoundSequenceOnPolyobj", "int polynum|str sndseq", ""),
  ...genFunction("SoundSequenceOnSector", "int tag|string seqname|int location", ""),
  ...genFunction("SoundVolume", "int tid|int channel|fixed volume", ""),
  ...genFunction("Spawn", "str classname|fixed x|fixed y|fixed z|[int tid]|[int angle]", ""),
  ...genFunction("SpawnDecal", "int tid|str decalname|[int flags]|[fixed angle]|[fixed zoffset]|[fixed distance]", ""),
  ...genFunction("SpawnForced", "str classname|fixed x|fixed y|fixed z|[int tid]|[int angle]", ""),
  ...genFunction("SpawnParticle", "int color|[bool fullbright]|[int lifetime]|[int size]|[fixed x]|[fixed y]|[fixed z]|[fixed velx]|[fixed vely]|[fixed velz]|[fixed accelx]|[fixed accely]|[fixed accelz]|[int startalpha]|[int fadestep]|[fixed endsize]", ""),
  ...genFunction("SpawnProjectile", "int tid|string type|int angle|int speed|int vspeed|int gravity|int newtid", ""),
  ...genFunction("SpawnSpot", "str classname|int spottid|[int tid]|[int angle]", ""),
  ...genFunction("SpawnSpotFacing", "str classname|int spottid|[int tid]", ""),
  ...genFunction("SpawnSpotFacingForced", "str classname|int spottid|[int tid]", ""),
  ...genFunction("SpawnSpotForced", "str classname|int spottid|[int tid]|[int angle]", ""),
  ...genFunction("Sqrt", "int number", ""),
  ...genFunction("StartSlideshow", "unknown parameter list", ""),
  ...genFunction("StopSound", "int tid|[int channel]", ""),
  ...genFunction("StrArg", "unknown parameter list", ""),
  ...genFunction("StrCaseCmp", "str string1|str string2|[int maxcomparenum]", ""),
  ...genFunction("StrCmp", "str string1|str string2|[int maxcomparenum]", ""),
  ...genFunction("StrCpy", "a:destination|string source|[int source_index]", ""),
  ...genFunction("StrIcmp", "str string1|str string2|[int maxcomparenum]", ""),
  ...genFunction("StrLeft", "str string|int length", ""),
  ...genFunction("StrLen", "str string", ""),
  ...genFunction("StrMid", "str string|int start|int length", ""),
  ...genFunction("StrParam", "type:expression", ""),
  ...genFunction("StrRight", "str string|int length", ""),
  ...genFunction("SwapActorTeleFog", "int tid", ""),
  ...genFunction("TagWait", "int tag", ""),
  ...genFunction("TakeActorInventory", "int tid|str inventory_item|int amount", ""),
  ...genFunction("TakeInventory", "str inventory_item|int amount", ""),
  ...genFunction("Thing_Damage2", "int tid|int amount|str type", ""),
  ...genFunction("Thing_Projectile2", "int tid|int type|int angle|int speed|int vspeed|int gravity|int newtid", ""),
  ...genFunction("ThingCount", "int type|int tid", ""),
  ...genFunction("ThingCountName", "str classname|int tid", ""),
  ...genFunction("ThingCountNameSector", "str classname|int tid|int tag", ""),
  ...genFunction("ThingCountSector", "int type|int tid|int tag", ""),
  ...genFunction("ThingSound", "int tid|str sound|int volume", ""),
  ...genFunction("Timer", "", ""),
  ...genFunction("UniqueTID", "[int tid]|[int limit]", ""),
  ...genFunction("UnMorphActor", "int tid|[bool force]", ""),
  ...genFunction("UseActorInventory", "int TID|str classname", ""),
  ...genFunction("UseInventory", "str classname", ""),
  ...genFunction("VectorAngle", "int x|int y", ""),
  ...genFunction("VectorLength", "int x|int y", ""),
  ...genFunction("Warp", "int tid|fixed xofs|fixed yofs|fixed zofs|fixed angle|int flags|[str success_state]|[bool exact]|[fixed heightoffset]|[fixed radiusoffset]|[fixed pitch]", ""),
  ...genFunction("Player_GiveItem", "unknown parameters list", ""),
  ...genFunction("Player_RemoveItem", "unknown parameters list", ""),
  ...genFunction("Player_SetTeam", "int team", ""),
  ...genFunction("Team_GivePoints", "int team|int points|int announce", ""),
  ...genFunction("Team_Score", "int points|int nogrin", ""),
  ...genFunction("AnnouncerSound", "str sound|int flags", ""),
  ...genFunction("BeginDBTransaction", "", ""),
  ...genFunction("BlueCount", "", ""),
  ...genFunction("BlueScore", "", ""),
  ...genFunction("BlueTeamCount", "", ""),
  ...genFunction("BlueTeamScore", "", ""),
  ...genFunction("ConsoleCommand", "str command", ""),
  ...genFunction("ConsolePlayerNumber", "", ""),
  ...genFunction("CountDBResults", "unknown parameters list", ""),
  ...genFunction("EndDBTransaction", "", ""),
  ...genFunction("FreeDBResults", "unknown parameters list", ""),
  ...genFunction("GetDBEntries", "unknown parameters list", ""),
  ...genFunction("GetDBEntry", "str table|str variable", ""),
  ...genFunction("GetDBEntryRank", "unknown parameters list", ""),
  ...genFunction("GetDBEntryString", "unknown parameters list", ""),
  ...genFunction("GetDBResultKeyString", "unknown parameters list", ""),
  ...genFunction("GetDBResultValue", "unknown parameters list", ""),
  ...genFunction("GetDBResultValueString", "unknown parameters list", ""),
  ...genFunction("GetGamemodeState", "", ""),
  ...genFunction("GetInvasionState", "", ""),
  ...genFunction("GetInvasionWave", "", ""),
  ...genFunction("GetPlayerAccountName", "unknown parameters list", ""),
  ...genFunction("GetPlayerLivesLeft", "int player", ""),
  ...genFunction("GetTeamProperty", "int team|int property", ""),
  ...genFunction("GetTimeProperty", "int timestamp|int which|[int utc]", ""),
  ...genFunction("IncrementDBEntry", "unknown parameters list", ""),
  ...genFunction("IsMultiplayer", "Checks if the game is currently a multiplayer game.", ""),
  ...genFunction("IsNetworkGame", "", ""),
  ...genFunction("IsOneFlagCTF", "", ""),
  ...genFunction("KickFromGame", "int player|str reason", ""),
  ...genFunction("Music_Change", "str music|int pattern", ""),
  ...genFunction("NamedRequestScriptPuke", "str script|[int arg0]|[int arg1]|[int arg2]|[int arg3]", ""),
  ...genFunction("PlayerArmorPoints", "", ""),
  ...genFunction("PlayerHealth", "", ""),
  ...genFunction("PlayerIsLoggedIn", "int playernumber", ""),
  ...genFunction("PlayerIsSpectator", "int player", ""),
  ...genFunction("PlayerTeam", "", ""),
  ...genFunction("RedCount", "", ""),
  ...genFunction("RedScore", "", ""),
  ...genFunction("RedTeamCount", "", ""),
  ...genFunction("RedTeamScore", "", ""),
  ...genFunction("RequestScriptPuke", "int script|int arg0|int arg1|int arg2", ""),
  ...genFunction("ResetMap", "", ""),
  ...genFunction("SetActivatorToPlayer", "int playernumber", "A replacement solution for AAPTR_PLAYERx that works with all 64 players instead of only 8"),
  ...genFunction("SetDBEntry", "str table|str variable|int value", ""),
  ...genFunction("SetDBEntryString", "unknown parameters list", ""),
  ...genFunction("SetDeadSpectator", "int playernumber|int deadspectator", "Turn alive players into dead spectators (deadspectator == 1) and revive dead spectators (deadspectator == 0)"),
  ...genFunction("SetPlayerLivesLeft", "int player|int amount", ""),
  ...genFunction("SinglePlayer", "", ""),
  ...genFunction("SortDBEntries", "unknown parameters list", ""),
  ...genFunction("Strftime", "int timestamp|str format|[int utc]", ""),
  ...genFunction("SystemTime", "", ""),
  ...genFunction("GetTeamScore", "int team", ""),
  ...genFunction("SetTeamScore", "int team|int score", ""),
] as ICompletionTree[];